// ===================================================
// DONNÉES TARIFAIRES — Camping Radar
// Prix par NUIT pour un mobil-home cœur de gamme (2-3ch)
// Structure: tableaux de tranches de dates avec prix min/max
// ===================================================

// Utilitaire : convertit "YYYY-MM-DD" en timestamp
function d(str) { return new Date(str).getTime(); }

// Pour chaque camping : tableau de tranches
// { from: "YYYY-MM-DD", to: "YYYY-MM-DD", min: €/nuit, max: €/nuit, semaine: €/sem }
// Les tranches couvrent du 01/01/2026 au 31/12/2026

const CAMPINGS = [
  {
    id: 1,
    nom: "La Tour des Prises",
    commune: "La Couarde-sur-Mer",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.2,
    nb_avis: 992,
    capacite: "200 emplacements",
    types_hebergement: ["Emplacements nus", "Mobil-homes", "Coco Sweet (insolite)"],
    services: ["Piscines (ext. chauffée + couverte)", "Pataugeoire", "Supérette", "Location vélos", "Pétanque", "Volley", "WiFi gratuit", "Sanitaires chauffés"],
    points_forts: ["Clos de mur, entouré de vignes", "600m de la plage", "Accès cyclables", "Calme – pas d'animations", "90% clients étrangers", "Vue vignoble"],
    positionnement: "Calme & nature",
    url: "https://www.camping-iledere.com",
    plateformes: ["Booking.com", "Homair", "Campings.fr"],
    is_target: true,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-01", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-02", to: "2026-04-30", min: 55 , max: 80 , semaine: 385  },
      { from: "2026-05-01", to: "2026-06-30", min: 60 , max: 95 , semaine: 420  },
      { from: "2026-07-01", to: "2026-07-31", min: 100, max: 175, semaine: 700  },
      { from: "2026-08-01", to: "2026-08-31", min: 120, max: 244, semaine: 840  },
      { from: "2026-09-01", to: "2026-09-25", min: 55 , max: 95 , semaine: 385  },
      { from: "2026-09-26", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 2,
    nom: "La Grainetière (Homair)",
    commune: "La Flotte-en-Ré",
    zone: "ile-de-re",
    etoiles: 5,
    note: 4.7,
    nb_avis: 2090,
    capacite: "280 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscines", "Toboggan aquatique", "Bar", "Épicerie", "Animations enfants", "Tennis", "Location vélos", "WiFi"],
    points_forts: ["5 étoiles", "Réseau Homair / Marvilla Parks", "Ambiance familiale", "Proche village La Flotte"],
    positionnement: "Familial haut de gamme",
    url: "https://www.la-grainetiere.com",
    plateformes: ["Homair", "Marvilla Parks", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 50 , max: 70 , semaine: 350  },
      { from: "2026-05-01", to: "2026-06-30", min: 60 , max: 90 , semaine: 420  },
      { from: "2026-07-01", to: "2026-07-31", min: 139, max: 200, semaine: 976  },
      { from: "2026-08-01", to: "2026-08-31", min: 187, max: 280, semaine: 1312  },
      { from: "2026-09-01", to: "2026-10-31", min: 49 , max: 75 , semaine: 343  },
      { from: "2026-11-01", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 3,
    nom: "Eden Villages L'Océan & Spa",
    commune: "La Couarde-sur-Mer",
    zone: "ile-de-re",
    etoiles: 5,
    note: 4.4,
    nb_avis: 3078,
    capacite: "338 emplacements",
    types_hebergement: ["Mobil-homes Premium", "Tentes lodge", "Emplacements nus"],
    services: ["Spa 300m²", "Piscines", "Bar-restaurant", "Jacuzzi privatif", "Animations quotidiennes", "Vélos", "WiFi"],
    points_forts: ["Concurrent direct (même commune)", "Spa 300m²", "5 étoiles", "Mobil-homes avec jacuzzi privé"],
    positionnement: "Luxe & bien-être",
    url: "https://www.eden-villages.fr/campings/ocean/",
    plateformes: ["Eden Villages", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 67 , max: 95 , semaine: 467  },
      { from: "2026-05-01", to: "2026-06-30", min: 75 , max: 110, semaine: 523  },
      { from: "2026-07-01", to: "2026-07-31", min: 130, max: 200, semaine: 910  },
      { from: "2026-08-01", to: "2026-08-31", min: 150, max: 230, semaine: 1050  },
      { from: "2026-09-01", to: "2026-09-27", min: 70 , max: 100, semaine: 490  },
      { from: "2026-09-28", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 4,
    nom: "Sandaya Interlude",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 5,
    note: 4.1,
    nb_avis: 1350,
    capacite: "250 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscines", "Toboggan", "Bar-restaurant", "Animations", "WiFi", "Épicerie"],
    points_forts: ["Réseau Sandaya", "5 étoiles", "Prix compétitifs pour un 5★"],
    positionnement: "Familial animé",
    url: "https://www.sandaya.fr/nos-campings/interlude",
    plateformes: ["Sandaya", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 55 , max: 85 , semaine: 385  },
      { from: "2026-05-01", to: "2026-06-30", min: 45 , max: 90 , semaine: 315  },
      { from: "2026-07-01", to: "2026-07-31", min: 120, max: 185, semaine: 840  },
      { from: "2026-08-01", to: "2026-08-31", min: 140, max: 215, semaine: 980  },
      { from: "2026-09-01", to: "2026-10-04", min: 50 , max: 90 , semaine: 350  },
      { from: "2026-10-05", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 5,
    nom: "Le Cormoran (Romanée)",
    commune: "Ars-en-Ré",
    zone: "ile-de-re",
    etoiles: 5,
    note: 4.6,
    nb_avis: 1397,
    capacite: "210 emplacements",
    types_hebergement: ["Mobil-homes Exclusif avec spa privatif", "Emplacements nus", "Tentes"],
    services: ["Piscine", "Spa privatif par mobil-home", "Bar", "Épicerie", "Animations", "Vélos"],
    points_forts: ["Mobil-homes avec spa privatif unique", "Ars-en-Ré pittoresque", "5 étoiles"],
    positionnement: "Luxe intime",
    url: "https://www.camping-ile-de-re-cormoran.com",
    plateformes: ["Romanée", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-05-01", min: 64 , max: 119, semaine: 448  },
      { from: "2026-05-02", to: "2026-05-29", min: 65 , max: 116, semaine: 455  },
      { from: "2026-05-30", to: "2026-06-12", min: 84 , max: 142, semaine: 588  },
      { from: "2026-06-13", to: "2026-07-03", min: 70 , max: 125, semaine: 490  },
      { from: "2026-07-04", to: "2026-07-17", min: 100, max: 213, semaine: 700  },
      { from: "2026-07-18", to: "2026-08-14", min: 104, max: 215, semaine: 728  },
      { from: "2026-08-15", to: "2026-08-28", min: 100, max: 213, semaine: 700  },
      { from: "2026-08-29", to: "2026-09-27", min: 64 , max: 115, semaine: 448  },
      { from: "2026-09-28", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 6,
    nom: "Le Phare – Collection Rivages",
    commune: "Les Portes-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.4,
    nb_avis: 1373,
    capacite: "Petite structure",
    types_hebergement: ["Cabanes premium", "Beach House", "Emplacements"],
    services: ["Piscine naturelle", "Spa", "Restaurant", "Yoga", "Location vélos", "Boutique"],
    points_forts: ["Positionnement ultra-premium", "Les Portes-en-Ré exclusif", "Collection Rivages prestige"],
    positionnement: "Ultra-luxe boutique",
    url: "https://www.lephare-iledere.com/fr",
    plateformes: ["Collection Rivages"],
    is_target: false,
    outlier: true, // Hôtel de plein air ultra-luxe, tarifs hors catégorie mobil-home standard
    tarifs: [
      { from: "2026-01-01", to: "2026-03-27", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-03-28", to: "2026-04-30", min: 102, max: 250, semaine: 715  },
      { from: "2026-05-01", to: "2026-06-30", min: 143, max: 400, semaine: 1000  },
      { from: "2026-07-01", to: "2026-07-31", min: 357, max: 700, semaine: 2500  },
      { from: "2026-08-01", to: "2026-08-31", min: 400, max: 900, semaine: 2800  },
      { from: "2026-09-01", to: "2026-09-27", min: 100, max: 350, semaine: 700  },
      { from: "2026-09-28", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 7,
    nom: "La Plage (Romanée)",
    commune: "Saint-Clément-des-Baleines",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.3,
    nb_avis: 335,
    capacite: "200 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus", "Lodges"],
    services: ["Piscine", "Bar", "Épicerie", "Animations", "Vélos"],
    points_forts: ["Proximité plage", "Groupe Romanée", "Vue mer pour certains hébergements"],
    positionnement: "Familial bord de mer",
    url: "https://www.la-plage-camping-ile-de-re.com",
    plateformes: ["Romanée", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-03-31", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-01", to: "2026-04-30", min: 58 , max: 93 , semaine: 405  },
      { from: "2026-05-01", to: "2026-06-30", min: 58 , max: 107, semaine: 405  },
      { from: "2026-07-01", to: "2026-07-31", min: 107, max: 200, semaine: 750  },
      { from: "2026-08-01", to: "2026-08-31", min: 120, max: 220, semaine: 840  },
      { from: "2026-09-01", to: "2026-09-30", min: 48 , max: 93 , semaine: 333  },
      { from: "2026-10-01", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 8,
    nom: "Les Ilates (Odalys / Flower)",
    commune: "Loix",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.0,
    nb_avis: 1449,
    capacite: "160 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Toboggan", "Bar", "Épicerie", "Animations", "Vélos"],
    points_forts: ["Village de Loix pittoresque", "Réseau Odalys/Flower", "Cadre naturel"],
    positionnement: "Nature & authenticité",
    url: "https://www.camping-loix.com",
    plateformes: ["Odalys", "Flower Camping", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 33 , max: 79 , semaine: 229  },
      { from: "2026-05-01", to: "2026-06-30", min: 64 , max: 112, semaine: 449  },
      { from: "2026-07-01", to: "2026-07-31", min: 112, max: 175, semaine: 784  },
      { from: "2026-08-01", to: "2026-08-31", min: 128, max: 204, semaine: 896  },
      { from: "2026-09-01", to: "2026-10-31", min: 33 , max: 92 , semaine: 229  },
      { from: "2026-11-01", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 9,
    nom: "Tamarins Plage (Odalys / Flower)",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 3.9,
    nb_avis: 137,
    capacite: "210 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "Animations", "Vélos", "WiFi"],
    points_forts: ["Bois-Plage populaire", "Réseau Odalys", "Accès plage"],
    positionnement: "Familial animé",
    url: "https://www.odalys-vacances.com/location-mer/poitou-charentes/ile-de-re/tamarins-plage.html",
    plateformes: ["Odalys", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 57 , max: 100, semaine: 400  },
      { from: "2026-05-01", to: "2026-06-30", min: 70 , max: 118, semaine: 490  },
      { from: "2026-07-01", to: "2026-07-31", min: 162, max: 195, semaine: 1134  },
      { from: "2026-08-01", to: "2026-08-31", min: 162, max: 210, semaine: 1134  },
      { from: "2026-09-01", to: "2026-09-27", min: 57 , max: 100, semaine: 400  },
      { from: "2026-09-28", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 10,
    nom: "Le Suroit (APV)",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.0,
    nb_avis: 933,
    capacite: "290 emplacements",
    types_hebergement: ["Mobil-homes", "Archipel premium", "Emplacements nus"],
    services: ["Piscines", "Bar", "Épicerie", "Animations", "Vélos", "WiFi"],
    points_forts: ["Grande capacité", "Réseau APV", "Bon rapport qualité-prix"],
    positionnement: "Volume & rapport qualité-prix",
    url: "https://www.lesuroit.fr",
    plateformes: ["APV", "Booking.com", "Campings.fr"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 58 , max: 101, semaine: 411  },
      { from: "2026-05-01", to: "2026-06-30", min: 59 , max: 113, semaine: 412  },
      { from: "2026-07-01", to: "2026-07-31", min: 90 , max: 171, semaine: 625  },
      { from: "2026-08-01", to: "2026-08-31", min: 100, max: 195, semaine: 700  },
      { from: "2026-09-01", to: "2026-09-27", min: 48 , max: 95 , semaine: 333  },
      { from: "2026-09-28", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 11,
    nom: "Au Val de Loire en Ré (APV)",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.1,
    nb_avis: 370,
    capacite: "200 emplacements",
    types_hebergement: ["Mobil-homes 3ch Grand Confort", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "Animations", "Vélos", "WiFi"],
    points_forts: ["Réseau APV", "Mobil-homes spacieux", "Prix accessibles pour 4★"],
    positionnement: "Familial accessible",
    url: "https://www.camping-apv.com/atlantique/camping-ile-de-re/",
    plateformes: ["APV", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-03", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-04", to: "2026-04-30", min: 61 , max: 80 , semaine: 410  },
      { from: "2026-05-01", to: "2026-06-30", min: 70 , max: 110, semaine: 490  },
      { from: "2026-07-01", to: "2026-07-31", min: 140, max: 219, semaine: 980  },
      { from: "2026-08-01", to: "2026-08-31", min: 160, max: 219, semaine: 1120  },
      { from: "2026-09-01", to: "2026-09-20", min: 61 , max: 90 , semaine: 424  },
      { from: "2026-09-21", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 12,
    nom: "APV Antioche",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.0,
    nb_avis: 276,
    capacite: "190 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "Animations", "Vélos"],
    points_forts: ["Réseau APV", "Proche plage", "Tarifs compétitifs"],
    positionnement: "Familial accessible",
    url: "https://www.camping-apv.com/atlantique/camping-ile-de-re/",
    plateformes: ["APV", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-03", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-04", to: "2026-04-30", min: 42 , max: 65 , semaine: 294  },
      { from: "2026-05-01", to: "2026-06-30", min: 38 , max: 80 , semaine: 269  },
      { from: "2026-07-01", to: "2026-07-31", min: 134, max: 216, semaine: 942  },
      { from: "2026-08-01", to: "2026-08-31", min: 134, max: 216, semaine: 941  },
      { from: "2026-09-01", to: "2026-09-20", min: 38 , max: 70 , semaine: 270  },
      { from: "2026-09-21", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 13,
    nom: "Les Varennes",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.4,
    nb_avis: 1331,
    capacite: "250 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Spa", "Bar", "Épicerie", "Animations", "Vélos", "WiFi"],
    points_forts: ["Excellente note (4,4)", "Spa sur place", "Nombreux avis positifs"],
    positionnement: "Qualité & sérénité",
    url: "https://www.les-varennes.com",
    plateformes: ["Booking.com", "Campings.fr"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-03-31", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-01", to: "2026-04-30", min: 57 , max: 108, semaine: 400  },
      { from: "2026-05-01", to: "2026-06-30", min: 57 , max: 140, semaine: 438  },
      { from: "2026-07-01", to: "2026-07-31", min: 120, max: 200, semaine: 840  },
      { from: "2026-08-01", to: "2026-08-31", min: 140, max: 220, semaine: 980  },
      { from: "2026-09-01", to: "2026-10-31", min: 53 , max: 100, semaine: 370  },
      { from: "2026-11-01", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 14,
    nom: "Slow Village Saint-Martin-de-Ré",
    commune: "Saint-Martin-de-Ré",
    zone: "ile-de-re",
    etoiles: 5,
    note: 4.3,
    nb_avis: 298,
    capacite: "50 emplacements (boutique)",
    types_hebergement: ["Cabanes sur pilotis", "Tentes lodge premium", "Tiny houses"],
    services: ["Piscine naturelle", "Bar-restaurant bio", "Spa", "Yoga", "Zéro déchet", "Pas de voitures"],
    points_forts: ["Concept éco-luxe unique", "Zéro voiture / pied de vignes", "Prix ultra-premium"],
    positionnement: "Éco-luxe & slow life",
    url: "https://www.slow-village.com/destinations/nouvelle-aquitaine/ile-de-re/",
    plateformes: ["Slow Village", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-02", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-03", to: "2026-04-30", min: 75 , max: 130, semaine: 361  },
      { from: "2026-05-01", to: "2026-06-30", min: 85 , max: 150, semaine: 449  },
      { from: "2026-07-01", to: "2026-07-31", min: 200, max: 457, semaine: 1400  },
      { from: "2026-08-01", to: "2026-08-31", min: 418, max: 457, semaine: 2926  },
      { from: "2026-09-01", to: "2026-11-02", min: 75 , max: 150, semaine: 361  },
      { from: "2026-11-03", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 15,
    nom: "Huttopia Chardons Bleus",
    commune: "Sainte-Marie-de-Ré",
    zone: "ile-de-re",
    etoiles: 3,
    note: 4.7,
    nb_avis: 619,
    capacite: "180 emplacements",
    types_hebergement: ["Tentes Huttopia", "Chalets en bois", "Emplacements nus"],
    services: ["Piscine naturelle", "Bar-restaurant", "Épicerie bio", "Animations nature", "Vélos"],
    points_forts: ["Meilleure note de l'île (4,8)", "Concept éco nature", "Prix abordables"],
    positionnement: "Nature & écologie",
    url: "https://europe.huttopia.com/site/chardonbleus-ile-de-re/",
    plateformes: ["Huttopia", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-01", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-02", to: "2026-04-30", min: 77 , max: 130, semaine: 432  },
      { from: "2026-05-01", to: "2026-06-30", min: 90 , max: 160, semaine: 504  },
      { from: "2026-07-01", to: "2026-07-31", min: 150, max: 280, semaine: 1050  },
      { from: "2026-08-01", to: "2026-08-31", min: 170, max: 314, semaine: 1190  },
      { from: "2026-09-01", to: "2026-11-01", min: 77 , max: 130, semaine: 432  },
      { from: "2026-11-02", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 16,
    nom: "Les Sables",
    commune: "Aytré",
    zone: "la-rochelle",
    etoiles: 4,
    note: 3.6,
    nb_avis: 772,
    capacite: "200 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "WiFi", "Animations"],
    points_forts: ["Proche La Rochelle", "Tarifs accessibles"],
    positionnement: "Budget / entrée de gamme",
    url: "https://camping-les-sables.com",
    plateformes: ["Booking.com", "Campings.fr"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-03-31", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-01", to: "2026-06-27", min: 43 , max: 65 , semaine: 300  },
      { from: "2026-06-28", to: "2026-07-04", min: 64 , max: 80 , semaine: 450  },
      { from: "2026-07-05", to: "2026-08-29", min: 100, max: 140, semaine: 700  },
      { from: "2026-08-30", to: "2026-10-15", min: 43 , max: 65 , semaine: 300  },
      { from: "2026-10-16", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 17,
    nom: "Le Beaulieu",
    commune: "Puilboreau",
    zone: "la-rochelle",
    etoiles: 4,
    note: 4.0,
    nb_avis: 968,
    capacite: "180 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "WiFi"],
    points_forts: ["Accès facile La Rochelle", "Tarifs limités"],
    positionnement: "Pratique & central",
    url: "https://www.camping-la-rochelle.com",
    plateformes: ["Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-03-31", min: 47 , max: 83 , semaine: 329  },
      { from: "2026-04-01", to: "2026-04-30", min: 47 , max: 95 , semaine: 452  },
      { from: "2026-05-01", to: "2026-06-30", min: 55 , max: 110, semaine: 536  },
      { from: "2026-07-01", to: "2026-07-31", min: 83 , max: 165, semaine: 850  },
      { from: "2026-08-01", to: "2026-08-31", min: 100, max: 165, semaine: 980  },
      { from: "2026-09-01", to: "2026-11-01", min: 47 , max: 95 , semaine: 452  },
      { from: "2026-11-02", to: "2026-12-31", min: 47 , max: 83 , semaine: 329  }
    ]
  },
  {
    id: 18,
    nom: "À la Corniche (Camping Paradis)",
    commune: "Angoulins-sur-Mer",
    zone: "la-rochelle",
    etoiles: 4,
    note: 3.9,
    nb_avis: 3293,
    capacite: "150 emplacements",
    types_hebergement: ["Mobil-homes", "Emplacements nus"],
    services: ["Piscine", "Bar", "Épicerie", "Animations", "WiFi"],
    points_forts: ["Label Camping Paradis", "Vue mer possible"],
    positionnement: "Familial label Camping Paradis",
    url: "https://camping-la-rochelle-alacorniche.com",
    plateformes: ["Camping Paradis", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-03-31", min: 40 , max: 55 , semaine: 291  },
      { from: "2026-04-01", to: "2026-04-30", min: 31 , max: 64 , semaine: 219  },
      { from: "2026-05-01", to: "2026-06-27", min: 44 , max: 88 , semaine: 307  },
      { from: "2026-06-28", to: "2026-07-31", min: 80 , max: 170, semaine: 560  },
      { from: "2026-08-01", to: "2026-08-31", min: 120, max: 240, semaine: 840  },
      { from: "2026-09-01", to: "2026-10-31", min: 40 , max: 80 , semaine: 291  },
      { from: "2026-11-01", to: "2026-12-31", min: 40 , max: 55 , semaine: 291  }
    ]
  },
  {
    id: 19,
    nom: "Au Port Punay",
    commune: "Châtelaillon-Plage",
    zone: "la-rochelle",
    etoiles: 4,
    note: 4.5,
    nb_avis: 742,
    capacite: "200 emplacements",
    types_hebergement: ["Mobil-homes", "Tentes lodge", "Emplacements nus"],
    services: ["Piscine", "Bar-restaurant", "Épicerie", "Animations", "WiFi", "Accès plage direct"],
    points_forts: ["Meilleure note La Rochelle (4,5)", "Accès direct plage", "Châtelaillon-Plage prisé"],
    positionnement: "Premium bord de mer",
    url: "https://www.camping-port-punay.com",
    plateformes: ["Booking.com", "Campings.fr"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-05-06", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-05-07", to: "2026-06-27", min: 52 , max: 132, semaine: 364  },
      { from: "2026-06-28", to: "2026-07-04", min: 88 , max: 172, semaine: 616  },
      { from: "2026-07-05", to: "2026-07-25", min: 119, max: 257, semaine: 833  },
      { from: "2026-07-26", to: "2026-08-17", min: 157, max: 257, semaine: 1099  },
      { from: "2026-08-18", to: "2026-08-29", min: 88 , max: 257, semaine: 616  },
      { from: "2026-08-30", to: "2026-09-14", min: 52 , max: 124, semaine: 364  },
      { from: "2026-09-15", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },

  {
    id: 20,
    nom: "L'Île Blanche",
    commune: "La Flotte-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 4.2,
    nb_avis: 189,
    capacite: "50 hébergements (parc 4ha)",
    types_hebergement: ["Mobil-homes", "Cottages (Glénans, Maldives, Florès)"],
    services: ["Piscine couverte & chauffée", "Espace aquatique", "Restaurant", "Location vélos", "Aire de jeux", "Boulodrome", "WiFi gratuit", "Gestion familiale"],
    points_forts: ["Parc boisé de 4 hectares", "Gestion familiale depuis 1986", "Cottages bois haut de gamme", "Calme & nature", "1,7km de la plage"],
    positionnement: "Calme & nature",
    url: "https://www.ile-blanche.com",
    plateformes: ["Direct", "CampingDirect", "Campings-Atlantique"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-03", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-04", to: "2026-05-01", min: 57 , max: 85 , semaine: 399  },
      { from: "2026-05-02", to: "2026-06-12", min: 60 , max: 91 , semaine: 420  },
      { from: "2026-06-13", to: "2026-07-03", min: 65 , max: 98 , semaine: 455  },
      { from: "2026-07-04", to: "2026-07-17", min: 119, max: 171, semaine: 833  },
      { from: "2026-07-18", to: "2026-08-21", min: 145, max: 206, semaine: 1015  },
      { from: "2026-08-22", to: "2026-08-28", min: 100, max: 159, semaine: 700  },
      { from: "2026-08-29", to: "2026-09-11", min: 67 , max: 89 , semaine: 469  },
      { from: "2026-09-12", to: "2026-09-26", min: 57 , max: 85 , semaine: 399  },
      { from: "2026-09-27", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
  {
    id: 21,
    nom: "Capfun La Bonne Étoile",
    commune: "Le Bois-Plage-en-Ré",
    zone: "ile-de-re",
    etoiles: 4,
    note: 3.7,
    nb_avis: 219,
    capacite: "202 emplacements locatifs",
    types_hebergement: ["Mobil-homes", "Chalets", "Roulottes"],
    services: ["Piscine couverte & chauffée", "Pataugeoire", "Toboggans", "Restaurant", "Snack", "Bar", "WiFi gratuit", "Club enfants & ados", "Location vélos"],
    points_forts: ["1,5km de la plage", "Animations vacances scolaires", "Vaste choix de locatifs Capfun", "Espace aquatique ludique", "Pavillon Bleu"],
    positionnement: "Familial animé",
    url: "https://www.camping-bonne-etoile.fr",
    plateformes: ["Capfun.com", "CampingDirect", "Booking.com"],
    is_target: false,
    tarifs: [
      { from: "2026-01-01", to: "2026-04-03", min: 0,   max: 0,   semaine: 0    },
      { from: "2026-04-04", to: "2026-04-30", min: 43 , max: 71 , semaine: 300  },
      { from: "2026-05-01", to: "2026-06-27", min: 50 , max: 93 , semaine: 350  },
      { from: "2026-06-28", to: "2026-07-31", min: 100, max: 164, semaine: 700  },
      { from: "2026-08-01", to: "2026-08-31", min: 129, max: 200, semaine: 900  },
      { from: "2026-09-01", to: "2026-10-31", min: 43 , max: 86 , semaine: 300  },
      { from: "2026-11-01", to: "2026-12-31", min: 0,   max: 0,   semaine: 0    }
    ]
  },
];

// ===== HÉBERGEMENTS MOBIL-HOMES par camping =====
const HEBERGEMENTS = {
  1: [
    { nom: 'EXCLUSIVE mobile home - 3 bedrooms - 2 shower rooms - private SPA', surface: '65m²', chambres: '3', capacite: '6 people', equipements: 'Dishwasher, 2 bathrooms, 2 toilets, Air conditioning, TV, Terrace, Private SPA/Hot tub, Top-of-the-range amenities, Pets allowed', prix_ref: 'From 652.5€ - 1075€ per stay', premium: true },
    { nom: 'EXCLUSIVE mobile home - 2 bedrooms - 2 shower rooms - SPA', surface: '63m²', chambres: '2', capacite: '4 people', equipements: 'Dishwasher, 2 bathrooms, 2 toilets, Air conditioning, TV, Terrace, Private SPA/Hot tub, Top-of-the-range amenities, Pets allowed', prix_ref: 'From 499.5€ - 746.1€ per stay', premium: true },
    { nom: 'EXCLUSIVE mobile home - 3 bedrooms - 2 bathrooms', surface: '65m²', chambres: '3', capacite: '6 people', equipements: 'Dishwasher, 2 bathrooms, 2 toilets, Air conditioning, TV, Terrace, Top-of-the-range amenities, Pets allowed', prix_ref: 'From 499.5€ - 1075€ per stay', premium: true },
    { nom: 'EXCLUSIVE mobile home - 2 bedrooms - 2 shower rooms', surface: '63m²', chambres: '2', capacite: '4 people', equipements: 'Dishwasher, 2 bathrooms, 2 toilets, Air conditioning, TV, Terrace, Top-of-the-range amenities, Pets allowed', prix_ref: 'From 467.1€ - 791.1€ per stay', premium: true },
    { nom: 'Mobil-home PREMIUM - 3 bedrooms', surface: '48m²', chambres: '3', capacite: '6 people', equipements: 'Dishwasher, Bathroom, Toilets, Air conditioning, TV, Terrace, Pets allowed', prix_ref: 'From 544.5€ - 805€ per stay', premium: true },
    { nom: 'Mobil-home PREMIUM - 2 bedrooms', surface: '45m²', chambres: '2', capacite: '4 people', equipements: 'Dishwasher, Bathroom, Toilets, Air conditioning, TV, Terrace, Pets allowed', prix_ref: 'From 486€ - 720€ per stay', premium: true },
    { nom: 'Mobil-home PREMIUM - 1 bedroom', surface: '35m²', chambres: '1', capacite: '2 people', equipements: 'Dishwasher, Bathroom, Toilets, Air conditioning, TV, Terrace, Pets allowed', prix_ref: 'From 396€ - 580€ per stay', premium: true },
    { nom: 'Mobil-home CONFORT - 3 bedrooms - Air-conditioned', surface: '41m²', chambres: '3', capacite: '6 people', equipements: 'Bathroom, Toilets, Air conditioning, TV, Terrace, Pets allowed', prix_ref: 'From 403.2€ - 596€ per stay', premium: false },
    { nom: 'Mobil-home CONFORT - 3 bedrooms', surface: '41m²', chambres: '3', capacite: '6 people', equipements: 'Bathroom, Toilets, TV, Terrace, Pets allowed', prix_ref: 'From 365.4€ - 542€ per stay', premium: false },
    { nom: 'Mobil-home CONFORT - 2 bedrooms - Air-conditioned', surface: '37m²', chambres: '2', capacite: '4 people', equipements: 'Bathroom, Toilets, Air conditioning, TV, Terrace, Pets allowed', prix_ref: 'From 360€ - 530€ per stay', premium: false },
    { nom: 'Mobil-home CONFORT - 2 bedrooms', surface: '37m²', chambres: '2', capacite: '4 people', equipements: 'Bathroom, Toilets, TV, Terrace, Pets allowed', prix_ref: 'From 324€ - 480€ per stay', premium: false },
    { nom: 'Mobil-home CONFORT - 2 bedrooms - PMR', surface: '37m²', chambres: '2', capacite: '4 people', equipements: 'Bathroom, Toilets, TV, Terrace (suitable for PMR), Pets allowed', prix_ref: 'From 324€ per stay', premium: false },
  ],
  2: [
    { nom: 'Mobil-home ULTIMATE', surface: '33-34 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Reversible Air Conditioning, Bed linen, Towels, Beds made on arrival, End of stay cleaning included, Lounge Terrace, Barbecue/plancha (optional), Choice of terrace.', prix_ref: 'From 651€ for 7 nights (sampled May 2026)', premium: true },
    { nom: 'Mobil-home PREMIUM (2 bedrooms)', surface: '29-31 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Reversible Air Conditioning, Barbecue/plancha, Raised Terrace, Choice of terrace (optional).', prix_ref: 'From 427€ for 7 nights (sampled Sept 2026)', premium: true },
    { nom: 'Mobil-home PREMIUM (3 bedrooms)', surface: '35-39 m²', chambres: '3', capacite: '6 persons', equipements: 'Television, Barbecue/plancha, Reversible Air Conditioning (optional), Raised Terrace.', prix_ref: 'From 525€ for 7 nights (sampled Sept 2026)', premium: true },
    { nom: 'Mobil-home COMFORT (2 bedrooms)', surface: '26-30 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Barbecue/plancha, Reversible Air Conditioning (optional), Raised Terrace, Choice of terrace (optional).', prix_ref: 'From 364€ for 7 nights (sampled Oct 2026)', premium: false },
    { nom: 'Mobil-home PMR COMFORT (Accessible)', surface: '36 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Reversible Air Conditioning, Barbecue/plancha, Raised Terrace (PMR adapted).', prix_ref: 'From 392€ for 7 nights (sampled Oct 2026)', premium: false },
    { nom: 'Mobil-home COMFORT (3 bedrooms)', surface: '32-37 m²', chambres: '3', capacite: '6 persons', equipements: 'Television, Reversible Air Conditioning, Barbecue/plancha, Raised Terrace.', prix_ref: 'From 476€ for 7 nights (sampled Oct 2026)', premium: false },
    { nom: 'Mobil-home CLASSIC (2 bedrooms)', surface: '30-31 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Raised Terrace, Garden furniture.', prix_ref: 'From 343€ for 7 nights (sampled Oct 2026)', premium: false },
    { nom: 'Mobil-home CLASSIC (3 bedrooms)', surface: '31 m²', chambres: '3', capacite: '6 persons', equipements: 'Television, Reversible Air Conditioning, Raised Terrace.', prix_ref: 'From 364€ for 7 nights (sampled Sept 2026)', premium: false },
    { nom: 'Cabane en bois (Wooden Cabin)', surface: '22 m²', chambres: '2', capacite: '4 persons', equipements: 'Television, Equipped Terrace.', prix_ref: 'From 294€ for 7 nights (sampled Oct 2026)', premium: false },
  ],
  3: [
    { nom: 'Océane Premium Spa 3 ch', surface: '~35m²', chambres: '3', capacite: '6', equipements: 'Climatisation, Lave-vaisselle, Jacuzzi, WiFi gratuit, Couettes/Oreillers fournis', prix_ref: '~850€ - 1200€ (April high end)', premium: true },
    { nom: 'Océane Premium Spa 2 ch', surface: '~32m²', chambres: '2', capacite: '4', equipements: 'Climatisation, Lave-vaisselle, Jacuzzi, WiFi gratuit, Couettes/Oreillers fournis', prix_ref: '~800€ - 1100€ (April high end)', premium: true },
    { nom: 'Mobil-home Plage / Saline / Evasion', surface: '28-30m²', chambres: '2', capacite: '4', equipements: 'Climatisation, Lave-vaisselle, WiFi gratuit, Couettes/Oreillers fournis', prix_ref: '580€ - 822€ (April)', premium: false },
    { nom: 'Mobil-home Grand Large / Privilège / Horizon', surface: '31-33m²', chambres: '3', capacite: '6', equipements: 'Climatisation, Lave-vaisselle (Grand Large/Privilège), WiFi gratuit', prix_ref: '636€ - 750€ (April)', premium: false },
    { nom: 'Mobil-home Plus 2ch / 3ch', surface: '28-31m²', chambres: '2-3', capacite: '4-6', equipements: 'WiFi gratuit, Couettes/Oreillers fournis (Pas de clim/LV sur gamme Plus)', prix_ref: '550€ - 636€ (April)', premium: false },
  ],
  4: [
    { nom: 'Cottage Premium Quartier Embrun', surface: '38m²', chambres: '3', capacite: '6 personnes', equipements: 'Lit Double Queen size (160x200cm), Wifi, Lave-vaisselle, Draps et serviettes inclus, Ménage de fin de séjour, Télévision, Cafetière à dosettes, Kit bébé, Salon de jardin, Bains de soleil, Etendoir à linge, Climatisation réversible.', prix_ref: 'Non spécifié (à partir de 45€/nuit selon offres générales)', premium: true },
    { nom: 'Cottage Luxe 4 Coquillages', surface: '60m²', chambres: '3', capacite: '6 personnes', equipements: 'Lit Double Queen size (160x200cm), Kit bébé, Draps et serviettes inclus, Bouilloire, Lave-vaisselle, Cafetière électrique, Coffre-fort, Sèche-cheveux, Plancha, Terrasse semi-couverte, Salon de jardin, Bains de soleil, Wifi, Climatisation réversible. Multi-module (2 modules).', prix_ref: 'Non spécifié', premium: true },
    { nom: 'Cottage Supérieur 4 Coquillages (6p)', surface: '38m²', chambres: '3', capacite: '6 personnes', equipements: 'Lit Double Queen size (160x200cm), Kit bébé, Draps et serviettes inclus, Wifi, Lave-vaisselle, Cafetière Nespresso, Télévision, Sèche-cheveux, Salon de jardin, Bains de soleil, Climatisation réversible.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Supérieur 4 Coquillages (4p)', surface: '38m²', chambres: '2', capacite: '4 personnes', equipements: 'Lit Double Queen size (160x200cm), Kit bébé, Draps et serviettes inclus, Wifi, Lave-vaisselle, Cafetière Nespresso, Télévision, Sèche-cheveux, Salon de jardin, Bains de soleil, Climatisation réversible.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Friends 4 Coquillages', surface: '120m²', chambres: '5', capacite: '10 personnes', equipements: 'Lit Double Queen size (160x200cm), Wifi, Lave-vaisselle, TV, Climatisation, Plancha, Salon de jardin, Bains de soleil, Etendoir à linge. Multi-module (3 modules).', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage 4 Coquillages (6p 38m2)', surface: '38m²', chambres: '3', capacite: '6 personnes', equipements: 'Lave-vaisselle, Télévision, Wifi, Salon de jardin, Bains de soleil, Chauffage, Cafetière électrique.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Taos 4 Coquillages', surface: '38m²', chambres: '2', capacite: '4 personnes', equipements: 'Lave-vaisselle, Télévision, Wifi, Salon de jardin, Bains de soleil, Chauffage, Cafetière électrique.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Dune 4 Coquillages', surface: '34m²', chambres: '2', capacite: '4 personnes', equipements: 'Lave-vaisselle, Télévision, Wifi, Salon de jardin, Bains de soleil, Chauffage, Cafetière électrique.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Galet 4 Coquillages', surface: '32m²', chambres: '2', capacite: '4 personnes', equipements: 'Lave-vaisselle, Télévision, Wifi, Salon de jardin, Bains de soleil, Chauffage, Cafetière électrique.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage Confort 3 Coquillages', surface: '31m²', chambres: '3', capacite: '6 personnes', equipements: 'Micro-ondes, Réfrigérateur, Plaque de cuisson, Cafetière électrique, Wifi, Salon de jardin, Bains de soleil.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage 3 Coquillages (4p 29m2)', surface: '29m²', chambres: '2', capacite: '4 personnes', equipements: 'Micro-ondes, Réfrigérateur, Plaque de cuisson, Cafetière électrique, Wifi, Salon de jardin, Bains de soleil.', prix_ref: 'Non spécifié', premium: false },
    { nom: 'Cottage 3 Coquillages PMR', surface: '34m²', chambres: '2', capacite: '4 personnes', equipements: 'Accès PMR, Télévision, Wifi, Lave-vaisselle, Salon de jardin, Bains de soleil, Chauffage.', prix_ref: 'Non spécifié', premium: false },
  ],
  5: [
    { nom: 'Mobil-home EXCLUSIF – 3 chambres – 2 salles d’eau – SPA privatif', surface: '65m²', chambres: '3', capacite: '6 people', equipements: 'Kitchen, Dishwasher, 2 Bathrooms, 2 Toilets, AC, TV, Terrace, Private SPA, Pets allowed', prix_ref: 'Starting from ~652.5€ for specific dates in April', premium: true },
    { nom: 'Mobil-home EXCLUSIF – 2 chambres – 2 salles d’eau – SPA', surface: '63m²', chambres: '2', capacite: '4 people', equipements: 'Kitchen, Dishwasher, 2 Bathrooms, 2 Toilets, AC, TV, Terrace, SPA, Pets allowed', prix_ref: 'Starting from ~746.1€ for specific dates in April', premium: true },
    { nom: 'Mobil-home EXCLUSIF – 3 chambres – 2 salles d’eau', surface: '65m²', chambres: '3', capacite: '6 people', equipements: 'Kitchen, Dishwasher, 2 Bathrooms, 2 Toilets, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~733.5€ for specific dates in April', premium: true },
    { nom: 'Mobil-home EXCLUSIF – 2 chambres – 2 salles d’eau', surface: '41m² (Estimated from Premium/Confort scales)', chambres: '2', capacite: '4 people', equipements: 'Kitchen, Dishwasher, 2 Bathrooms, 2 Toilets, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~683.1€ for specific dates in April', premium: true },
    { nom: 'Mobil-home PREMIUM – 3 chambres', surface: '48m²', chambres: '3', capacite: '6 people', equipements: 'Kitchen, Dishwasher, Bathroom, Toilet, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~544.5€ for specific dates in April', premium: true },
    { nom: 'Mobil-home PREMIUM – 2 chambres', surface: '~40-45m² (Estimated)', chambres: '2', capacite: '4 people', equipements: 'Kitchen, Dishwasher, Bathroom, Toilet, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~486€ for specific dates in April', premium: true },
    { nom: 'Mobil-home PREMIUM – 1 chambre', surface: '35m²', chambres: '1', capacite: '2 people', equipements: 'Kitchen, Dishwasher, Bathroom, Toilet, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~396€ for specific dates in April', premium: true },
    { nom: 'Mobil-home CONFORT – 3 chambres – Climatisé', surface: '41m²', chambres: '3', capacite: '6 people', equipements: 'Kitchen, Bathroom, Toilet, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~403.2€ for specific dates in April', premium: false },
    { nom: 'Mobil-home CONFORT – 3 chambres', surface: '~35-40m² (Estimated)', chambres: '3', capacite: '6 people', equipements: 'Kitchen, Bathroom, Toilet, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~365.4€ for specific dates in April', premium: false },
    { nom: 'Mobil-home CONFORT – 2 chambres – Climatisé', surface: '~30-35m² (Estimated)', chambres: '2', capacite: '4-5 people (Typical)', equipements: 'Kitchen, Bathroom, Toilet, AC, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~360€ for specific dates in April', premium: false },
    { nom: 'Mobil-home CONFORT – 2 chambres', surface: '~30-35m² (Estimated)', chambres: '2', capacite: '4-5 people (Typical)', equipements: 'Kitchen, Bathroom, Toilet, TV, Terrace, Pets allowed', prix_ref: 'Starting from ~324€ for specific dates in April', premium: false },
    { nom: 'Mobil-home CONFORT – 2 chambres – PMR', surface: '37m²', chambres: '2', capacite: '4 people', equipements: 'Kitchen, Bathroom, Toilet, TV, Terrace (adapted), Pets allowed, PMR Access', prix_ref: 'Starting from ~324€ for specific dates in April', premium: false },
  ],
  6: [
    { nom: 'Villa Beach House', surface: '75m²', chambres: '3 (1 double 160*200, 2 with 2 single lits 80*190)', capacite: 'Jusqu’à 6 personnes', equipements: 'Bain nordique chauffé, cuisine tout équipée (micro-ondes combiné, plaques à induction, Nespresso, lave-vaisselle, réfrigérateur/congélateur, bouilloire, grille-pain), TV, climatisation réversible, Wifi, grande terrasse, mobilier de jardin, transats, barbecue à gaz, lits faits à l\'arrivée, linge de maison inclus.', prix_ref: 'Non visible sans dates de séjour', premium: true },
    { nom: 'Beach House avec bain nordique', surface: '39m²', chambres: '2 (1 double 160*200, 1 with 2 singles 80*190)', capacite: 'Jusqu’à 4 personnes', equipements: 'Bain nordique, cuisine équipée (micro-ondes combiné, induction, Nespresso, lave-vaisselle, réfrigérateur/congélateur), 2 salles de bain, TV, climatisation, Wifi, terrasse, mobilier de jardin, lits faits à l\'arrivée.', prix_ref: 'Non visible sans dates de séjour', premium: true },
    { nom: 'Beach House 2 chambres', surface: '39m²', chambres: '2 (1 double 160*200, 1 with 2 singles 80*190)', capacite: 'Jusqu’à 4 personnes', equipements: 'Cuisine équipée (micro-ondes combiné, induction, Nespresso, lave-vaisselle, réfrigérateur/congélateur), 2 salles de bain, TV, climatisation, Wifi, terrasse, mobilier de jardin, lits faits à l\'arrivée.', prix_ref: 'Non visible sans dates de séjour', premium: false },
    { nom: 'Cabane de Ré 2 chambres', surface: '29m²', chambres: '2 (1 double 160*200, 1 with 2 singles 80*190) + canapé convertible', capacite: 'Jusqu’à 6 personnes', equipements: 'Cuisine équipée (micro-ondes, plaques au gaz, Nespresso, lave-vaisselle, réfrigérateur/congélateur), TV, climatisation, Wifi, terrasse, mobilier de jardin, 2 transats, linge de maison inclus.', prix_ref: 'Non visible sans dates de séjour', premium: false },
    { nom: 'Cabane de Ré 2 chambres Premium', surface: '33 m²', chambres: '2 (1 double 160*200, 1 with 2 singles 80*190)', capacite: 'Jusqu’à 4 personnes', equipements: '2 salles de bain, 2 WC séparés, cuisine équipée, TV, climatisation, Wifi, terrasse, linge de maison inclus.', prix_ref: 'Non visible sans dates de séjour', premium: true },
    { nom: 'Cabane de Ré 3 chambres', surface: '34m²', chambres: '3 (1 double 160*200, 2 with 2 singles 80*190)', capacite: 'Jusqu’à 6 personnes', equipements: 'Cuisine équipée, TV, climatisation, Wifi, terrasse, linge de maison inclus.', prix_ref: 'Non visible sans dates de séjour', premium: false },
    { nom: 'Cabane de Ré 3 chambres Premium', surface: '40 m²', chambres: '3 (1 double 160*200, 2 with 2 singles 80*190)', capacite: 'Jusqu’à 6 personnes', equipements: '2 salles de bain, 2 WC séparés, cuisine équipée, TV, climatisation, Wifi, terrasse, linge de maison inclus.', prix_ref: 'Non visible sans dates de séjour', premium: true },
    { nom: 'Loulou Lodge 2 chambres', surface: '29m²', chambres: '2 (1 double, 1 twin) + canapé convertible', capacite: 'Jusqu’à 4 personnes', equipements: 'Cuisine équipée (lave-vaisselle, réfrigérateur/congélateur, micro-ondes, Senseo, bouilloire, grille-pain), TV, climatisation, Wifi, terrasse, mobilier de jardin, transats. Linge de maison NON inclus.', prix_ref: 'Non visible sans dates de séjour', premium: false },
  ],
  7: [
    { nom: 'Mobil-home CONFORT - 2 chambres', surface: '37m² (including 12m² terrace)', chambres: '2', capacite: '4 persons', equipements: 'Terrace, Kitchen (fridge, freezer, microwave, coffee machine), Bathroom, WC, Animals allowed.', prix_ref: 'From 189€ to 302€ depending on dates', premium: false },
    { nom: 'Mobil-home CONFORT - 2 chambres - PMR', surface: '~37m²', chambres: '2', capacite: '4 persons', equipements: 'Terrace, Kitchen, Bathroom, WC, PMR access features.', prix_ref: 'Similar to standard Confort 2ch', premium: false },
    { nom: 'Mobil-home CONFORT - 2 chambres - Climatisé', surface: '~37m²', chambres: '2', capacite: '4 persons', equipements: 'Air Conditioning, Terrace, Kitchen, Bathroom, WC.', prix_ref: 'From 202€ to 326€ depending on dates', premium: false },
    { nom: 'Mobil-home PREMIUM - 1 chambre', surface: 'N/A', chambres: '1', capacite: '2 persons', equipements: 'High-end equipment, Kitchen, Bathroom, WC, Terrace, TV, AC.', prix_ref: 'From 243€ to 378€ depending on dates', premium: true },
    { nom: 'Mobil-home PREMIUM - 2 chambres', surface: '45m²', chambres: '2', capacite: '4 persons', equipements: 'Dishwasher, Air Conditioning, TV, Terrace, Kitchen, Bathroom, WC.', prix_ref: 'From 270€ to 548€ depending on dates', premium: true },
    { nom: 'Mobil-home PREMIUM - 3 chambres', surface: 'N/A', chambres: '3', capacite: '6 persons', equipements: 'Dishwasher, Air Conditioning, TV, Terrace, Kitchen, Bathroom, WC.', prix_ref: 'From 297€ to 614€ depending on dates', premium: true },
    { nom: 'Mobil-home EXCLUSIF - 2 chambres - 2 salles d’eau - SPA privatif', surface: 'N/A', chambres: '2', capacite: '4 persons', equipements: 'Private SPA (Jacuzzi), 2 Bathrooms, 2 WC, Dishwasher, AC, TV, Large Terrace.', prix_ref: 'From 459€ to 973€ depending on dates', premium: true },
    { nom: 'Mobil-home EXCLUSIF - 3 chambres - 2 salles d’eau - SPA privatif', surface: '65m²', chambres: '3', capacite: '6 persons', equipements: 'Private SPA (Jacuzzi), 2 Bathrooms, 2 WC, Dishwasher, AC, TV, Very Large Terrace, High-end furniture.', prix_ref: 'From 513€ to 1067€ depending on dates', premium: true },
    { nom: 'Tente CONFORT - 2 chambres - sans sanitaire', surface: 'N/A', chambres: '2', capacite: '4 persons', equipements: 'No bathroom/sanitary facilities, 2 bedrooms, kitchenette.', prix_ref: 'From 132€ to 316€ depending on dates', premium: false },
    { nom: 'Lodge PREMIUM - 2/3 chambres - sans sanitaire', surface: 'N/A', chambres: '2 or 3', capacite: '4-6 persons', equipements: 'No bathroom/sanitary facilities, premium finishes, terrace.', prix_ref: 'N/A', premium: true },
  ],
  8: [
    { nom: 'HOMEFLOWER PREMIUM PLUS JACUZZI 29M² (2 CHAMBRES)', surface: '29m²', chambres: '2', capacite: '4', equipements: 'Jacuzzi, Lits faits à l\'arrivée, Ménage de fin de séjour, TV, Terrasse (implied by series)', prix_ref: 'Dès 599€ (original 1008€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM PLUS 35M² (3 CHAMBRES)', surface: '35m²', chambres: '3', capacite: '6', equipements: 'Lits faits à l\'arrivée, Ménage de fin de séjour, TV, Terrasse, Kitchen appliances', prix_ref: 'Dès 804€ (original 1005€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM PLUS 29M² (2 CHAMBRES)', surface: '29m²', chambres: '2', capacite: '4', equipements: 'Lits faits à l\'arrivée, Ménage de fin de séjour, TV, Terrasse, Kitchen appliances', prix_ref: 'Dès 449€ (original 847€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM AVEC JACUZZI – 35M² (3 CHAMBRES)', surface: '35m²', chambres: '3', capacite: '6', equipements: 'Jacuzzi, Terrasse, TV, Plancha, Clim (AC), Kitchen appliances', prix_ref: 'Dès 659€ (original 1029€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM 35M² (3 CHAMBRES)', surface: '35m²', chambres: '3', capacite: '6', equipements: 'Clim (AC), Terrasse semi-couverte, TV, Draps (sheets), Serviettes (towels), Kitchen appliances', prix_ref: 'Dès 549€ (original 900€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM 29M² (2 CHAMBRES)', surface: '29m²', chambres: '2', capacite: '4', equipements: 'Clim (AC), Terrasse semi-couverte, TV, Draps (sheets), Serviettes (towels), Kitchen appliances', prix_ref: 'Dès 349€ (original 777€)', premium: true },
    { nom: 'HOMEFLOWER PREMIUM AVEC JACUZZI – 29M² (2 CHAMBRES)', surface: '29m²', chambres: '2', capacite: '4', equipements: 'Jacuzzi, Terrasse semi-couverte, TV, Plancha, Clim (AC), Kitchen appliances', prix_ref: 'Dès 499€ (original 942€)', premium: true },
    { nom: 'MOBIL-HOME CONFORT 31M² (3 CHAMBRES)', surface: '31m²', chambres: '3', capacite: '6', equipements: 'TV, Terrasse semi-couverte, Kitchen appliances', prix_ref: 'Dès 499€ (original 812€)', premium: false },
    { nom: 'MOBIL-HOME CONFORT 27,5M² (2 CHAMBRES)', surface: '27.5m²', chambres: '2', capacite: '4', equipements: 'TV, Terrasse semi-couverte, Kitchen appliances', prix_ref: 'Dès 289€ (original 671€)', premium: false },
    { nom: 'MOBIL-HOME PMR CONFORT 27,5M² (2 CHAMBRES)', surface: '27.5m²', chambres: '2', capacite: '4', equipements: 'Adapted for people with reduced mobility (PMR), TV, Kitchen appliances', prix_ref: 'Dès 536.8€ (original 671€)', premium: false },
    { nom: 'MAISONNETTE PMR STANDARD 31M² (1 CHAMBRE + BZ)', surface: '31m²', chambres: '1', capacite: '2', equipements: 'Adapted for people with reduced mobility (PMR), TV, Terrasse, BZ convertible, Kitchen appliances', prix_ref: 'Dès 516€ (original 645€)', premium: false },
    { nom: 'MAISONNETTE STANDARD 31M² (2 CHAMBRES)', surface: '31m²', chambres: '2', capacite: '4', equipements: 'TV, Terrasse, Kitchen appliances', prix_ref: 'Dès 279€ (original 645€)', premium: false },
    { nom: 'ECOLODGE COTTON TOILÉE CONFORT 35M² (3 CHAMBRES)', surface: '35m²', chambres: '3', capacite: '6', equipements: 'Terrasse couverte de 11m², TV, Kitchen appliances', prix_ref: 'Dès 499€ (original 673€)', premium: false },
    { nom: 'ECOLODGE COTTON TOILÉE CONFORT 35M² (2 CHAMBRES)', surface: '35m²', chambres: '2', capacite: '4', equipements: 'Terrasse couverte de 11m², TV, Kitchen appliances', prix_ref: 'Dès 289€ (original 596€)', premium: false },
    { nom: 'CABANE LODGE SUR PILOTIS STANDARD 34M² (2 CHAMBRES) - SANS SANITAIRES', surface: '34m²', chambres: '2', capacite: '4', equipements: 'Terrasse couverte 11m², Without bathrooms (sans sanitaires), Kitchen appliances', prix_ref: 'Dès 229€ (original 418€)', premium: false },
    { nom: 'CABANE LODGE SUR PILOTIS STANDARD 34M² (2 CHAMBRES) TV', surface: '34m²', chambres: '2', capacite: '4', equipements: 'TV, Terrasse couverte 11m², Kitchen appliances', prix_ref: 'Dès 229€ (original 515€)', premium: false },
  ],
  9: [
    { nom: 'Mobil Home 4/6 Personnes - Standard', surface: 'Not specified', chambres: '2-3', capacite: '4-6', equipements: 'Kitchen with stove and hob, TV, Large terrace', prix_ref: 'Not provided on homepage', premium: false },
    { nom: 'Mobil Home 6/8 Personnes - Standard', surface: 'Not specified', chambres: '3', capacite: '6-8', equipements: 'Kitchen with stove and hob, TV, Large terrace', prix_ref: 'Not provided on homepage', premium: false },
    { nom: 'Mobil Home Premium 4 Personnes', surface: '30', chambres: '2', capacite: '4', equipements: 'Kitchenette with refrigerator, hobs, dishes, utensils, TV, Terrace, Large bay windows, Linen and towels included', prix_ref: 'Not provided on homepage', premium: true },
    { nom: 'Mobil Home Premium 4 Personnes Climatisé', surface: '34', chambres: '2', capacite: '4', equipements: 'Fully equipped kitchen with dishwasher, hobs, refrigerator, dishes, utensils, TV, Large terrace, Bathroom, Air conditioning, Linen and towels included', prix_ref: 'Not provided on homepage', premium: true },
    { nom: 'Mobil Home Premium 6 Personnes Climatisé', surface: '34', chambres: '3', capacite: '6', equipements: 'Fully equipped kitchen with dishwasher, hobs, refrigerator, dishes, utensils, TV, Large terrace, Shower room, Air conditioning, Linen and towels included', prix_ref: 'Not provided on homepage', premium: true },
    { nom: 'Nomad Home Terra 4/6 Personnes', surface: 'Not specified', chambres: 'Not specified', capacite: '4-6', equipements: 'Kitchenette with refrigerator, electric hobs, microwave, sink, dishes and utensils, Shower room, WC, Large wooden terrace, Modern sleek design', prix_ref: 'Not provided on homepage', premium: true },
    { nom: 'Nomad Home Canopée 6/8 Personnes', surface: 'Not specified', chambres: 'Not specified', capacite: '6-8', equipements: 'Kitchenette with refrigerator, electric hobs, microwave, sink, dishes and utensils, Shower room, WC, Large wooden terrace, Modern sleek design', prix_ref: 'Not provided on homepage', premium: true },
    { nom: 'Tente Lodge sans Sanitaire 5 Personnes', surface: 'Not specified', chambres: '1-2', capacite: '5', equipements: 'Terrace with access stairs, Cozy cocooning ambiance, Mounted on platform or stilts', prix_ref: 'Not provided on homepage', premium: false },
    { nom: 'Tente Lodge Confort 4 Personnes', surface: 'Not specified', chambres: '2', capacite: '4', equipements: 'Large terrace, Modern glamping concept, Open design with nature views', prix_ref: 'Not provided on homepage', premium: false },
  ],
  10: [
    { nom: 'La Villa Roséa avec jacuzzi privatif', surface: '70 m²', chambres: '4 chambres', capacite: '8 personnes', equipements: '3 TV, Jacuzzi privatif, Climatisation, Lave-vaisselle, Lave linge, Cuisine d\'extérieure avec plancha gaz + kit barbecue, Salon de jardin, Draps et linge de toilette fournis (7 nuits min)', prix_ref: 'à partir de 1330 € la semaine', premium: true },
    { nom: 'La Villa Rhéa avec jacuzzi privatif', surface: '70 m²', chambres: '4 chambres', capacite: '8 personnes', equipements: '3 TV, Jacuzzi privatif, Climatisation, Lave-vaisselle, Lave linge, Plancha gaz + kit barbecue, Salon de jardin, Draps et linge de toilette fournis (7 nuits min)', prix_ref: 'à partir de 1330 € la semaine', premium: true },
    { nom: 'PREMIUM : Mobil home TV, 6 personnes, 3 chambres, 2 salles de bain', surface: '43 m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'TV, 2 salles de bain, Climatisation, Lave-vaisselle, Cuisine d\'extérieur avec plancha gaz, Quartier piéton, Draps et linge de toilette fournis (7 nuits min), Forfait ménage inclus (7 nuits min)', prix_ref: 'à partir de 770 € la semaine', premium: true },
    { nom: 'PREMIUM : Mobil home TV, 4 personnes, 2 chambres, 2 salles de bain', surface: '35 m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'TV, 2 salles de bain, Climatisation, Lave-vaisselle, Cuisine d\'extérieur avec plancha gaz, Quartier piéton, Draps et linge de toilette fournis (7 nuits min)', prix_ref: 'à partir de 680 € la semaine', premium: true },
    { nom: 'ARCHIPEL : 14 personnes, 7 chambres, jacuzzi privatif et climatisation', surface: '77 m² (40+37)', chambres: '7 chambres (2 mobil-homes)', capacite: '14 personnes', equipements: 'TV, Jacuzzi privatif, Climatisation, Lave-vaisselle, 4 salles de bain, Cuisine d\'extérieure avec plancha, Draps fournis (7 nuits min)', prix_ref: 'à partir de 1682 € la semaine', premium: false },
    { nom: 'ARCHIPEL : 8 personnes, 4 chambres avec climatisation', surface: '50 m² (32+18)', chambres: '4 chambres (2 mobil-homes)', capacite: '8 personnes', equipements: 'TV, Climatisation, Lave-vaisselle, 2 salles de bain, Plancha, Terrasse commune couverte', prix_ref: 'à partir de 975 € la semaine', premium: false },
    { nom: 'QUARTIER : Mobil-Home TV, 6 personnes, 3 chambres, Terrasse Couverte (Privilège)', surface: '34 m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'TV, Lave-vaisselle, Wifi gratuit, Barbecue gaz, Terrasse en bois semi-couverte, Draps fournis (1 semaine min)', prix_ref: 'à partir de 630 € la semaine', premium: false },
    { nom: 'QUARTIER : Mobil-Home TV, 5 personnes, 2 chambres, Terrasse Couverte (Privilège)', surface: '30 m² approx', chambres: '2 chambres', capacite: '5 personnes', equipements: 'TV, Lave-vaisselle, Wifi gratuit, Barbecue gaz, Terrasse en bois semi-couverte, Draps fournis (1 semaine min)', prix_ref: 'à partir de 595 € la semaine', premium: false },
    { nom: 'CLIMATISE : Mobile-home, 6 personnes, 3 chambres, Terrasse couverte', surface: '34 m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'TV, Climatisation, Lave-vaisselle, Wifi (1 connexion incluse), Terrasse couverte, 2 Chiliennes', prix_ref: 'à partir de 665 € la semaine (estimation)', premium: false },
    { nom: 'RHETAISE : Cabane rhétaise 6 personnes, 3 chambres', surface: '34 m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'TV gratuit, Lave-vaisselle, Wifi gratuit, Barbecue Gaz, Terrasse en bois couverte, Espace de stockage pour vélos, Draps fournis (1 semaine min)', prix_ref: 'à partir de 600 € la semaine', premium: false },
    { nom: 'CONFORT PLUS + : Mobile-Home, 6 personnes, 3 chambres, Terrasse couverte', surface: '30 m² approx', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse couverte', prix_ref: 'à partir de 539 € la semaine', premium: false },
    { nom: 'CONFORT PLUS + : Mobile-Home, 2 personnes, 1 chambre, Terrasse bois couverte', surface: '20 m²', chambres: '1 chambre', capacite: '2 personnes', equipements: 'TV en supplément, Wifi possible (payant), Terrasse en bois couverte, Salon de jardin', prix_ref: 'à partir de 399 € la semaine', premium: false },
    { nom: 'Mobil home « Accessible pour personnes à mobilité réduite » 4/6 pers. 2 ch. TV, Terrasse couverte', surface: '31 m²', chambres: '2 chambres', capacite: '4/6 personnes (PMR)', equipements: 'TV en supplément, Rampe d\'accès, Plan de travail rabaissé, Siège de douche, Terrasse couverte', prix_ref: 'NC (estimé autour de Confort Plus)', premium: false },
    { nom: 'CONFORT : Mobile-Home, 4/6 personnes, 2 chambres', surface: '28 m²', chambres: '2 chambres (+ sofa)', capacite: '4/6 personnes', equipements: 'TV en supplément, Wifi possible (payant), Salon de jardin, Terrasse au sol/bois/couverte selon modèle', prix_ref: 'à partir de 420 € la semaine', premium: false },
  ],
  11: [
    { nom: 'Mobil-home Grand Confort 6/8P', surface: '~28 m²', chambres: '3 bedrooms (1 double bed, 2 twin rooms)', capacite: '6/8 people', equipements: 'TV, wooden semi-covered terrace, kitchen (fridge, microwave, stovetop), 2 chiliennes/sun loungers, some with dishwasher (LV).', prix_ref: '467€ - 668€ / week', premium: true },
    { nom: 'Mobil-home Grand Confort 4/6P', surface: '~25-26 m²', chambres: '2 bedrooms (1 double bed, 1 twin room + convertible sofa)', capacite: '4/6 people', equipements: 'TV, wooden semi-covered terrace, kitchen (fridge, microwave, stovetop), 2 chiliennes.', prix_ref: '445€ - 637€ / week', premium: true },
    { nom: 'Mobil-home Grand Confort 4P', surface: '~20-22 m²', chambres: '2 bedrooms (1 double bed, 1 twin room)', capacite: '4 people', equipements: 'TV, wooden semi-covered terrace, kitchen (fridge, microwave), outdoor seating.', prix_ref: '426€ - 609€ / week', premium: true },
    { nom: 'Mobil-home Grand Confort PMR 4/6P', surface: '~30 m² (estimated)', chambres: '2 bedrooms (Adapted access)', capacite: '4/6 people', equipements: 'TV, terrace, kitchen, PMR adapted (disabled access).', prix_ref: '516€ - 738€ / week', premium: true },
    { nom: 'Mobil-home Confort 6/8P', surface: '~28 m²', chambres: '3 bedrooms', capacite: '6/8 people', equipements: 'TV, terrace, kitchen. Middle-range model (7-12 years old).', prix_ref: '445€ - 637€ / week', premium: false },
    { nom: 'Mobil-home Standard 6/8P', surface: '~28 m²', chambres: '3 bedrooms', capacite: '6/8 people', equipements: 'TV, terrace, kitchen. Basic model (>12 years old, well maintained).', prix_ref: '421€ - 602€ / week', premium: false },
    { nom: 'Mobil-home Standard 4/6P', surface: '~25 m²', chambres: '2 bedrooms', capacite: '4/6 people', equipements: 'TV, terrace, kitchen. Basic model (>12 years old).', prix_ref: '382€ - 546€ / week', premium: false },
    { nom: 'Mobil-home Standard 4P', surface: '~20 m²', chambres: '2 bedrooms', capacite: '4 people', equipements: 'TV, terrace, kitchen. Basic model (>12 years old).', prix_ref: '~400€ / week (avg)', premium: false },
    { nom: 'Mobil-home Eco 6/8P', surface: '~28 m²', chambres: '3 bedrooms', capacite: '6/8 people', equipements: 'TV, kitchen, simple comfort for reduced price.', prix_ref: '396€ - 567€ / week', premium: false },
    { nom: 'Tente Lodge 4P', surface: '~23 m²', chambres: '2 bedrooms', capacite: '4 people', equipements: 'Kitchenette (fridge, microwave, 2 burners, sink), integrated terrace. No sanitary (access to campsite blocks).', prix_ref: '281€ - 402€ / week', premium: false },
  ],
  13: [
    { nom: 'Mobil-home Plage', surface: '23,5m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, lit double (140 cm), deux lits simples (80 cm)', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Océane Premium SPA 3 chambres', surface: '40m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse podium en bois semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, Jacuzzi, volets roulants, lit double (160 cm), draps, serviettes et tapis de bain fournis, 2 salles de bain', prix_ref: 'Non visible', premium: true },
    { nom: 'Mobil-home Océane Premium SPA 2 chambres', surface: '31m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse podium en bois semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, Jacuzzi, volets roulants, cuisine avec hotte, draps, serviettes et tapis de bain fournis, 2 salles de bain', prix_ref: 'Non visible', premium: true },
    { nom: 'Mobil-home Saline', surface: '29m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse en bois semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, hotte, sèche-cheveux, télévision, lit double (160 cm), lits jumeaux', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Privilège', surface: '32m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse en bois semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, hotte, télévision, sèche-cheveux, stores occultants, lit double (160 cm), lits jumeaux', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Forêt', surface: '31m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse en bois semi-couverte, salon de jardin, transats, climatisation, chauffage, télévision', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Azur', surface: '28m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse en bois semi-couverte, salon de jardin, transats, climatisation, chauffage, télévision', prix_ref: 'Non visible, surface area: 28m²', premium: false },
    { nom: 'Mobil-home Grand Large', surface: '32m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, hotte, sèche-cheveux, télévision, lit double (160 cm), deux lits simples (80 cm), lit gigogne', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Horizon', surface: '32m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse semi-couverte, salon de jardin, transats, climatisation, chauffage, lit double (140 cm), deux lits simples (80 cm), lit gigogne', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Evasion', surface: '32m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse semi-couverte, salon de jardin, transats, climatisation, lave-vaisselle, hotte, sèche-cheveux, télévision, lit double (160 cm), lit gigogne, draps, serviettes et tapis de bain fournis', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Plus 2 chambres', surface: '25m²', chambres: '2 chambres', capacite: '4 personnes', equipements: 'Terrasse en dalles gravillonnées, salon de jardin, parasol, transats, chauffage, télévision', prix_ref: 'Non visible', premium: false },
    { nom: 'Mobil-home Plus 3 chambres', surface: '31m²', chambres: '3 chambres', capacite: '6 personnes', equipements: 'Terrasse en dalles gravillonnées, salon de jardin, transats, parasol, chauffage, télévision', prix_ref: 'Non visible', premium: false },
  ],
  14: [
    { nom: 'Slow House Signature 5ch.', surface: '100 m²', chambres: '5 bedrooms (3 on first floor, 2 on mezzanine)', capacite: '10 persons', equipements: '2 double beds (160*190), 2 single beds (90*190), 4 single beds (80*190), Refrigerator, Hotplate, Dishwasher, Senseo coffee maker, Kettle, Toaster, Microwave, 3 bathrooms, 2 separate WCs, Hair dryer, TV, Wi-Fi, Heating, Air conditioning, Terrace with pergola, Deckchairs, Sheets and towels provided, End-of-stay cleaning included.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Slow House Signature 6ch.', surface: '150 m²', chambres: '6 bedrooms', capacite: '12 persons', equipements: '2 double beds (160*190), 4 single beds (90*190), 4 single beds (80*190), Refrigerator, Hotplate, Dishwasher, Senseo coffee maker, Kettle, Toaster, Microwave, 3 bathrooms, 2 separate WCs, Hair dryer, TV, Wi-Fi, Heating, Air conditioning, Covered terrace, Deckchairs, Sheets and towels provided, End-of-stay cleaning included.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Slow House Signature 3bed.', surface: '75 m²', chambres: '3 bedrooms', capacite: '6 persons', equipements: '2 double beds (160*190), 2 single beds (80*190), Refrigerator, Hotplate, Dishwasher, Senseo coffee maker, Kettle, Toaster, Microwave, 2 bathrooms, 1 WC, Hair dryer, TV, Wi-Fi, Heating, Air conditioning, Covered terrace, Deckchairs, Sheets and towels provided, End-of-stay cleaning included.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Cabane Premium PMR 2ch. (Accessible)', surface: '35 m²', chambres: '2 bedrooms', capacite: '4 persons', equipements: 'Double bed (140*190), 1 high bed (70*190), 1 single bed (80*190) + 1 trundle bed, Refrigerator, Hotplate, Dishwasher, Filter coffee maker, Toaster, Microwave, Shower, separate WC, TV, Wi-Fi, Heating, Pergola, Sunbathing area, Sheets provided.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Cabane Premium 2ch.', surface: '35 m²', chambres: '2 bedrooms', capacite: '4 persons', equipements: 'Double bed (140*190), 1 high bed (70*190), 1 single bed (80*190) + 1 trundle bed, Refrigerator, Hotplate, Dishwasher, Senseo coffee maker, Toaster, Microwave, Shower, separate WC, TV, Wi-Fi, Heating, Pergola, Sunbathing area, Sheets provided.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Cabane Premium 3ch.', surface: '50 m²', chambres: '3 bedrooms (incl. mezzanine)', capacite: '6 persons', equipements: 'Double bed (160*190), 2 single beds (90*190) on mezzanine, 2 alcove beds (90*180) on mezzanine, Refrigerator, Hotplate, Dishwasher, Senseo coffee maker, Toaster, Microwave, Shower, separate WC, TV, Wi-Fi, Heating, Pergola, Sunbathing area, Sheets provided.', prix_ref: 'Varies by period (requires date selection)', premium: true },
    { nom: 'Comfort Plus Cabin, 2 bedrooms', surface: '25 m²', chambres: '2 bedrooms (incl. mezzanine)', capacite: '4 persons', equipements: 'Double bed (160*190), 2 alcove beds (90*180) on mezzanine, Refrigerator, Hotplate, Dishwasher, Filter coffee maker, Toaster, Microwave, Shower (70*70), WC, TV, Wi-Fi, Heating, Terrace with Chilean chairs.', prix_ref: 'Varies by period (requires date selection)', premium: false },
    { nom: 'Cabane Confort 2ch.', surface: '25 m²', chambres: '2 bedrooms (incl. mezzanine)', capacite: '4 persons', equipements: 'Double bed (160*190), 2 alcove beds (90*180) on mezzanine, Refrigerator, Hotplate, Dishwasher, Filter coffee maker, Toaster, Microwave, Shower (70*70), WC, TV, Wi-Fi, Heating, Terrace with Chilean chairs.', prix_ref: 'Varies by period (requires date selection)', premium: false },
    { nom: 'Cabane Tribu 4ch. (Cabane Confort Tribu)', surface: '2x25 m²', chambres: '4 bedrooms (double module)', capacite: '8 persons', equipements: '2 double beds (160*190), 4 alcove single beds (90*180) on mezzanine, Refrigerator, 2-burner hob, Dishwasher, Filter coffee maker, Microwave, 2 bathrooms (Showers 70x70), 2 separate WCs, Televisions, Wi-Fi, Heating, Plancha, Large shared terrace.', prix_ref: 'Varies by period (requires date selection)', premium: false },
  ],
  15: [
    { nom: 'Chalet Evasion', surface: '25 m²', chambres: '2 bedrooms (one double bed 140x200, one single bed and a bunk bed)', capacite: 'Up to 5 people', equipements: 'Equipped kitchen (sink, gas hob, microwave oven, fridge, electric coffee maker), living area, dining area, bathroom with shower, separate toilet, wooden terrace, electric heating, fan.', prix_ref: '€209 to €261/night (approx.)', premium: false },
    { nom: 'Chalet Ontario PRM (Disabled Access)', surface: '35 m²', chambres: '2 large bedrooms (master suite with double bed 160x200, second bedroom with single bunk bed 90x200)', capacite: 'Up to 4 people', equipements: 'Fitted kitchen (sink, induction hob, microwave oven, fridge, dishwasher, electric coffee maker), ultra spacious living room, 2 bathrooms (one with disabled shower cubicle), separate toilet, 17 m² terrace with access ramp, Fermob table and chairs, electric heating, fan.', prix_ref: '€209 to €261/night (approx.)', premium: false },
    { nom: 'Wood Trailer (Roulotte)', surface: '21 m²', chambres: '2 separate bedrooms (one double bed 140x200, one single bunk bed 70x190)', capacite: 'Up to 4 people (max 2 adults)', equipements: 'Equipped kitchen (sink, gas hob, microwave, fridge, electric coffee maker), living area with table and bench, bathroom with sink and shower, separate toilet, wooden picnic table, parasol, 2 pop-up armchairs, electric heating, fan.', prix_ref: '€183 to €235/night (approx.)', premium: false },
    { nom: 'Sweet Wood & Canvas Tent', surface: '25 m²', chambres: '2 bedrooms (one double bed 140x200, one single bed 80x190 and a bunk bed)', capacite: 'Up to 5 people', equipements: 'Kitchen area (sink, fridge, two hobs), bathroom with shower, washbasin and toilet, wooden terrace.', prix_ref: '€149 to €217/night (approx.)', premium: false },
    { nom: 'Classic Wood & Canvas Tent', surface: '20 m²', chambres: '2 bedrooms (one double bed 140x200, one double bed 140x190 and a single bunk bed 80x190)', capacite: 'Up to 5 people', equipements: 'Fully-equipped kitchenette (fridge, hob, storage, crockery), wooden terrace with parasol and two pop-up armchairs. No bathroom/toilet.', prix_ref: '€149 to €217/night (approx.)', premium: false },
  ],
  16: [
    { nom: 'Mobil-Home 1 chambre - Gamme Confort', surface: '18 m²', chambres: '1 (lit 140 cm)', capacite: '2 persons max', equipements: 'Kitchen equipped with microwave, filter coffee maker, toaster, gas hob, refrigerator with freezer, and utensils. Includes cleaning kit (broom, bucket, mop). Bed linen (sheets, pillows, blankets) provided. Semi-covered wooden terrace with garden furniture. Free WiFi.', prix_ref: 'Low Season: from 75€/night or 480€/week. High Season: 660€ - 910€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: false },
    { nom: 'Mobil-Home 2 chambres - Gamme Confort', surface: '28 m²', chambres: '2 (1x140cm, 2x80cm non-bunk)', capacite: '4 persons max', equipements: 'Kitchen equipped with microwave, filter coffee maker, toaster, gas hob, refrigerator with freezer, and utensils. Includes cleaning kit (broom, bucket, mop). Bed linen (sheets, pillows, blankets) provided. Semi-covered wooden terrace with garden furniture. Free WiFi. Available in PMR (accessible) version.', prix_ref: 'Low Season: from 95€/night or 630€/week. High Season: 810€ - 1110€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: false },
    { nom: 'Mobil-Home 2 chambres Clim - Gamme Confort', surface: '28 m² (approx.)', chambres: '2', capacite: '4 persons max', equipements: 'Same as 2-bedroom Confort, plus Air Conditioning (Climatisation).', prix_ref: 'Low Season: from 100€/night or 690€/week. High Season: 860€ - 1150€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: false },
    { nom: 'Mobil-Home 3 chambres - Gamme Confort', surface: '32 m²', chambres: '3 (1x140cm, 4x80cm in 2 rooms)', capacite: '6 persons max', equipements: 'Kitchen equipped with microwave, filter coffee maker, toaster, gas hob, refrigerator with freezer, and utensils. Includes cleaning kit (broom, bucket, mop). Bed linen (sheets, pillows, blankets) provided. Semi-covered wooden terrace with garden furniture. Free WiFi.', prix_ref: 'Low Season: from 120€/night or 780€/week. High Season: 960€ - 1200€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: false },
    { nom: 'Mobil-Home 3 chambres Clim - Gamme Confort', surface: '32 m² (approx.)', chambres: '3', capacite: '6 persons max', equipements: 'Same as 3-bedroom Confort, plus Air Conditioning (Climatisation).', prix_ref: 'Low Season: from 130€/night or 840€/week. High Season: 1000€ - 1250€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: false },
    { nom: 'Mobil-Home 2 chambres - Gamme MAXI confort (Clim)', surface: '40 m²', chambres: '2 (1x160cm with dressing, 2x80cm with dressing)', capacite: '4 persons max', equipements: 'High-end kitchen (microwave, coffee maker, toaster, gas hob, fridge-freezer, dishwasher). TV, stick vacuum, washing machine. Covered wooden terrace with garden furniture. 1 free spa session/day (+16y), beds made on arrival, bed linen provided. WiFi.', prix_ref: 'Low Season: from 155€/night or 1100€/week. High Season: 1300€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: true },
    { nom: 'Mobil-Home 2 chambres - Gamme Excellence (Confort Luxe)', surface: '40 m²', chambres: '2 (1x160cm with dressing and private shower, 2x80cm with dressing and private shower)', capacite: '4 persons max', equipements: 'Luxury kitchen (microwave, filter coffee maker, toaster, gas hob, fridge-freezer, dishwasher). TV, stick vacuum, washing machine, plancha, 2 sun loungers. 2 shower rooms and 2 toilets. Semi-covered wooden terrace. 1 free spa session/day/person (+16y), beds made on arrival, bed linen and towels provided. WiFi. No pets.', prix_ref: 'Low Season: from 170€/night or 1300€/week. High Season: 1500€/week. [Tarifs 2026](https://camping-les-sables.com/wp-content/uploads/2026/01/GRILLE-TARIFS-2026-CLS.pdf)', premium: true },
  ],
  17: [
    { nom: 'MOBIL-HOME FAMILIAL PRIVILÈGE PLUS', surface: '36m²', chambres: '3 (stated in text as 3, icons say 3)', capacite: '6', equipements: 'Equipped with transats, plancha, TV 80cm, double bed 160 Bultex. Covered terrace with wooden garden furniture and TV. Kitchen with stove.', prix_ref: 'Not visible in overview', premium: true },
    { nom: 'INSOLITE', surface: '17m²', chambres: '2', capacite: '4', equipements: '2 bedrooms, no sanitary facilities. Kitchenette with electric cooktop, refrigerator, microwave, crockery. Living room with 2 convertible benches into 70x190 beds. Electric heating, electrical outlets. Sheets and duvet covers provided. Double door with lock.', prix_ref: 'Not visible in overview', premium: false },
    { nom: 'MOBIL-HOME FAMILIAL PRIVILÈGE', surface: '33m²', chambres: '3', capacite: '6', equipements: '3 bedrooms, family accommodation, equipped with terrace and TV.', prix_ref: 'Not visible in overview', premium: true },
    { nom: 'MOBIL-HOME FAMILIAL', surface: '33m²', chambres: '3', capacite: '6', equipements: '3 bedrooms, family accommodation. All rentals have a terrace and TV.', prix_ref: 'Not visible in overview', premium: false },
    { nom: 'MOBIL-HOME PRIVILÈGE', surface: '29m²', chambres: '2', capacite: '4', equipements: '2 bedrooms, privileged range. All rentals have a terrace and TV.', prix_ref: 'Not visible in overview', premium: true },
    { nom: 'MOBIL-HOME PMR', surface: '30,5m²', chambres: '2', capacite: '4', equipements: '2 bedrooms, specifically designed for people with reduced mobility. Terrace and TV included.', prix_ref: 'Not visible in overview', premium: false },
    { nom: 'MOBIL-HOME PREMIUM', surface: '23m²', chambres: '2', capacite: '4', equipements: '2 bedrooms, premium range. Terrace and TV included.', prix_ref: 'Not visible in overview', premium: true },
    { nom: 'MOBIL-HOME CONFORT', surface: '23m²', chambres: '2', capacite: '4', equipements: '2 bedrooms, comfort range. Terrace and TV included.', prix_ref: 'Not visible in overview', premium: false },
    { nom: 'MOBIL-HOME CLASSIQUE', surface: '16m²', chambres: '1', capacite: '2', equipements: '1 bedroom, classic range. Terrace and TV included.', prix_ref: 'Not visible in overview', premium: false },
    { nom: 'MOBIL-HOME ÉCO', surface: '15m²', chambres: '1', capacite: '2', equipements: '2 adjoining modules. Covered terrace 9m² with wooden garden furniture. Kitchenette with 2-burner ceramic hob, 90L refrigerator, microwave, coffee maker, flat-screen TV. Shower room with shower, sink and WC. 1 bedroom with 140x190 bed. Pillows and blankets provided.', prix_ref: 'Starting from 343€ per week (visible in detailed view)', premium: false },
  ],
  18: [
    { nom: 'Mobile-Home 1 chambre Confort 2p', surface: '18m²', chambres: '1', capacite: '2', equipements: 'Double bed (140x190), kitchen (fridge-freezer, microwave, coffee maker, kettle), bathroom (shower, sink, WC), electric heating, private terrace with garden furniture.', prix_ref: 'Not specified', premium: false },
    { nom: 'Mobile-Home 2 chambres Confort 4p', surface: '22m² to 27m² (avg 26m²)', chambres: '2', capacite: '4', equipements: '1 double bed (140x190), 2 single beds (80x190), kitchen (sink, vitro 4 burners, hood, fridge-freezer, oven, microwave), TV, bathroom (shower, sink), separate WC, electric heating, covered terrace with garden furniture, Wi-Fi.', prix_ref: 'From 300€ for 6 nights', premium: false },
    { nom: 'Mobile-Home 3 chambres (until 6 persons)', surface: '34m²', chambres: '3', capacite: '6', equipements: '1 double bed (140x190), 4 single beds, kitchen (sink, 4 gas burners, hood, fridge-freezer, microwave, coffee maker, kettle, dishes), TV, bathroom (shower, sink), separate WC, semi-covered terrace with garden furniture.', prix_ref: 'Not specified', premium: false },
    { nom: 'Mobile-Home 4 CH Confort 8p', surface: '40m²', chambres: '4', capacite: '8', equipements: '2 double beds (140x190), 4 single beds (80x190), kitchen (sink, vitro 4 burners, hood, fridge-freezer, dishwasher, microwave, coffee maker, kettle), AC, TV, bathroom (shower, sink), separate WC, electric heating, covered terrace with garden furniture, Wi-Fi.', prix_ref: 'From 375€ for 5 nights', premium: true },
    { nom: 'Mobile-Home Mitoyen Standard 1ch 2p (Semi-detached)', surface: '17m²', chambres: '1', capacite: '2', equipements: 'Double bed (140x190), kitchen (sink, vitro 2 burners, oven, hood, fridge-freezer, microwave, coffee maker, kettle), TV, bathroom (shower, sink, WC), electric heating, covered terrace with garden furniture.', prix_ref: 'Not specified', premium: false },
    { nom: 'Mobile-Home PMR Confort 2 chambres 4p (Accessible)', surface: '30m² to 31m²', chambres: '2', capacite: '4', equipements: '1 double bed (140x190), 2 single beds (90x190), Italian shower with seat, integrated WC, equipped kitchen, wheelchair ramp access, sliding doors.', prix_ref: 'Not specified', premium: false },
    { nom: 'Cottage Confort 2 chambres 5p (Chalet style)', surface: '25m² to 28m²', chambres: '2', capacite: '5', equipements: '2 bedrooms (2 doubles + 1 bunk bed), kitchen (sink, vitro, hood, fridge-freezer, microwave, coffee maker), bathroom (shower, sink, WC), electric heating, semi-covered terrace with garden furniture. Listed under Chalets section.', prix_ref: 'Not specified', premium: false },
    { nom: 'Cottage Privilège 2 chambres 5p (Premium Chalet style)', surface: '25m² to 28m²', chambres: '2', capacite: '5', equipements: 'Sea view, AC (hot/cold), TV, 2 bedrooms (1 double + 1 double with bunk or 1 double + 3 singles), kitchen (vitro 4 burners, hood, fridge-freezer, microwave), bathroom (shower, sink, WC), semi-covered terrace with garden furniture. Listed under Chalets Privilège section.', prix_ref: 'Not specified', premium: true },
  ],
  19: [
    { nom: 'Les Embruns (Gamme Confort)', surface: '22.50 m² + 6.70 m² de terrasse', chambres: '2 chambres', capacite: '2 adultes + 2 enfants (max 12 ans)', equipements: 'Terrasse semi-couverte, salon de jardin, parasol, TV écran plat LCD, 4 feux gaz, réfrigérateur 96L, convecteur électrique, douche, lavabo, WC séparés, moustiquaires.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: false },
    { nom: 'Les Alizés (Gamme Confort)', surface: '24.20 m² + 7 m² de terrasse', chambres: '2 chambres', capacite: '4 personnes maximum', equipements: 'Terrasse semi-couverte, salon de jardin, parasol, TV écran plat LCD, 4 feux gaz, réfrigérateur 194L, convecteur électrique, douche, lavabo, WC séparés, moustiquaires.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: false },
    { nom: 'L\'Escale (Gamme Confort)', surface: '27.60 m² + 8.40 m² de terrasse', chambres: '3 chambres', capacite: '4 adultes + 2 enfants (max 12 ans)', equipements: 'Terrasse semi-couverte, salon de jardin, parasol, TV écran plat LCD, 4 feux gaz, réfrigérateur + congélateur 194L, convecteur électrique, douche, lavabo, WC séparés, moustiquaires.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: false },
    { nom: 'L\'Estran (Gamme Confort - PMR)', surface: '32.00 m² environ', chambres: '2 chambres', capacite: '4 personnes maximum (PMR)', equipements: 'Terrasse non couverte, salon de jardin, parasol, TV (TNT + étrangères), 4 feux gaz, réfrigérateur 134L, convecteur électrique, douche, lavabo et WC adaptés. Conçu pour les personnes à mobilité réduite.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: false },
    { nom: 'Les Flots (Gamme Premium)', surface: '25.60 m² + 6.70 m² de terrasse', chambres: '2 chambres', capacite: '4 personnes maximum', equipements: 'Terrasse semi-couverte, 2 bains de soleil, salon de jardin, lave-vaisselle, TV écran plat LCD, linge de lit et de toilette fournis, sèche-serviettes, sèche-cheveux, moustiquaires, 4 feux gaz, réfrigérateur 194L.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: true },
    { nom: 'Le Ponton (Cottage Premium)', surface: '28 m² + 7.80 m² de terrasse', chambres: '2 chambres (dont 1 en mezzanine)', capacite: '4 personnes maximum', equipements: 'Terrasse entièrement couverte avec partie bar, 2 bains de soleil, salon de jardin, lave-vaisselle, TV (TNT + étrangères), linge de lit et de toilette fournis, sèche-serviettes, sèche-cheveux, moustiquaires, 4 feux gaz, réfrigérateur + congélateur 194L.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: true },
    { nom: 'Les Cordées (Gamme Premium)', surface: '35.30 m² + 15 m² de terrasse', chambres: '3 chambres (dont 1 en mezzanine)', capacite: '4 adultes + 2 enfants (max 12 ans)', equipements: 'Grande terrasse (15 m²), parasol déporté, 2 bains de soleil, salon de jardin, lave-vaisselle, TV (TNT + étrangères), linge de lit et de toilette fournis, sèche-serviettes, sèche-cheveux, moustiquaires, 4 feux gaz, réfrigérateur + congélateur 194L.', prix_ref: 'Tarification dynamique (non affichée directement)', premium: true },
  ],
};

// ===== HELPER : prix pour une date donnée =====
function getPrixForDate(camping, dateStr) {
  if (!dateStr || !camping.tarifs) return { min: camping.tarifs[0].min, max: camping.tarifs[0].max, semaine: camping.tarifs[0].semaine };
  const ts = new Date(dateStr).getTime();
  const tranche = camping.tarifs.find(t => {
    return ts >= new Date(t.from).getTime() && ts <= new Date(t.to).getTime();
  });
  return tranche || camping.tarifs[0];
}

// ===== HELPER : prix total pour un séjour (date + nb nuits) =====
function getPrixSejour(camping, dateStr, nbNuits) {
  if (!dateStr || !nbNuits) return getPrixForDate(camping, dateStr);
  // Calcul jour par jour pour gérer les changements de tranche en cours de séjour
  let totalMin = 0, totalMax = 0;
  for (let i = 0; i < nbNuits; i++) {
    const current = new Date(dateStr);
    current.setDate(current.getDate() + i);
    const iso = current.toISOString().split('T')[0];
    const p = getPrixForDate(camping, iso);
    totalMin += p.min;
    totalMax += p.max;
  }
  return { min: Math.round(totalMin / nbNuits), max: Math.round(totalMax / nbNuits), total_min: totalMin, total_max: totalMax };
}
